// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByqQ8uuDSNuZYdN-CoWpqaAOL45Wo2Ivk',
    appId: '1:940804824190:web:fda6c5fcffdefe775d4c2f',
    messagingSenderId: '940804824190',
    projectId: 'discussit-77146',
    authDomain: 'discussit-77146.firebaseapp.com',
    storageBucket: 'discussit-77146.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnbqGafCEA6FqA0ePnvEKzIg--X90l6Uw',
    appId: '1:940804824190:android:697838d19a3958f15d4c2f',
    messagingSenderId: '940804824190',
    projectId: 'discussit-77146',
    storageBucket: 'discussit-77146.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVZD5SxGf0QYzvVmbeJ5AWADXaWuZx7E8',
    appId: '1:940804824190:ios:b3cdef1207d2d4995d4c2f',
    messagingSenderId: '940804824190',
    projectId: 'discussit-77146',
    storageBucket: 'discussit-77146.appspot.com',
    iosBundleId: 'com.example.discussIt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByqQ8uuDSNuZYdN-CoWpqaAOL45Wo2Ivk',
    appId: '1:940804824190:web:15910fa46cb4a4bf5d4c2f',
    messagingSenderId: '940804824190',
    projectId: 'discussit-77146',
    authDomain: 'discussit-77146.firebaseapp.com',
    storageBucket: 'discussit-77146.appspot.com',
  );
}
